services:
  db:
    image: postgres:16-alpine
    container_name: schoolibrary_db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-schoollib}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-schoollib123}
      POSTGRES_DB: ${DB_NAME:-schoolibrary}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
